GET http://localhost:3003/api/blogs/

###

POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "4.2 is done yay",
  "author": "jane doe maybe who knows",
  "url": "testurl.com",
  "likes": 2
}

###

PUT http://localhost:3003/api/blogs/6798a3b61a305584424d1774 HTTP/1.1
content-type: application/json

{
  "likes": 8
}