GET http://localhost:3003/api/blogs/

###

POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "jee jee toimii",
  "author": "jane doe maybe who knows",
  "url": "testurl.com",
  "likes": 2
}